# Generated by Django 5.1.4 on 2024-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
